export const images: Record<string, any> = {
  forward: require('../../assets/img/forward.png'),
  scan: require('../../assets/img/scan.png'),
  sliderimg: require('../../assets/img/sliderimg.png'),
  man: require('../../assets/img/man.png'),
  rightarrow: require('../../assets/img/rightarrow.png'),
  tshirt: require('../../assets/img/tshirt.jpg'),
  camera: require('../../assets/img/camera.png'),
  gallery: require('../../assets/img/gallery.png'),
  backarrow: require('../../assets/img/arrow_back.png'),
  uparrow: require('../../assets/img/up.png'),
  downarrow: require('../../assets/img/down.png'),
  favourite: require('../../assets/img/favorite.png'),
  rightwhite: require('../../assets/img/rightwhite.png'),
};
